Nitro eth deposit
OffchainLabs/arbitrum-subgraphs pull request #9
Opened 2022-10-25 15:54 UTC by gvladika

Make eth-deposit work for Nitro

2022-10-26 13:23 UTC, fredlacs requested changes

2022-10-27 15:22 UTC, fredlacs approved these changes
LGTM

2022-10-27 15:22 UTC, fredlacs commented on packages/arb-bridge-eth/tests/inbox/inbox.test.ts
> +})
skip line at end of file

2022-10-27 15:30 UTC, gvladika commented on packages/arb-bridge-eth/tests/inbox/inbox.test.ts
> +})
done

2022-10-27 16:27 UTC, merged